apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        imagePullPolicy: IfNotPresent
        image: muhammadehtesh/medium_angular_frontend:$(Build.BuildId) # your image file
        resources:
          limits:
            memory: "1Gi"
            cpu: "128m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  selector:
    app: angular-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000

